"""Dump the avocado scouting entries and the tree-name mapping for the push."""
import json

import frappe

OUT = "/tmp/claude-1001/-home-ubuntu-stive-code-frappe15-apps-upande-scp/b6c1bfb1-0cbb-4dc9-8993-2881a8b84c4a/scratchpad/"
CHILD = {
    "pests_scouting_entry": "Pests Scouting Entry",
    "diseases_scouting_entry": "Diseases Scouting Entry",
    "predators_scouting_entry": "Predators Scouting Entry",
    "weeds_scouting_entry": "Weeds Scouting Entry",
    "incidents_scouting_entry": "Incidents Scouting Entry",
    "physiological_disorders_entry": "Physiological Disorders Entry",
    "trap_scouting_entry": "Trap Scouting Entry",
    "crop_modelling_entry": "Crop Modelling Entry",
}


def run(limit=5000):
    # The tree names differ between sites: kaitet carries legacy import codes
    # (23HA_BLK1_ROW1_T1) while the target's were generated by the field
    # automation ("<row> - Tree <n>"). The row and the number are the bridge.
    tree_map = {}
    for t in frappe.get_all("Orchard Tree", fields=["name", "row", "tree", "tree_number"], limit_page_length=0):
        num = t.tree_number or t.tree
        if t.row and num:
            tree_map[t.name] = "{} - Tree {}".format(t.row, int(num))
    json.dump(tree_map, open(OUT + "tree_map.json", "w"))
    print("tree map entries:", len(tree_map))

    names = frappe.get_all(
        "Scouting Entry", filters={"crop_scouted": "Avocado"},
        pluck="name", order_by="creation asc", limit_page_length=limit,
    )
    print("avocado entries to dump:", len(names))

    docs, child_rows = [], 0
    meta_fields = [f.fieldname for f in frappe.get_meta("Scouting Entry").fields
                   if f.fieldtype not in ("Section Break", "Column Break", "Tab Break", "HTML", "Button")]
    for n in names:
        d = frappe.get_doc("Scouting Entry", n)
        row = {f: d.get(f) for f in meta_fields if d.get(f) not in (None, "")}
        row["name"] = d.name
        row["doctype"] = "Scouting Entry"
        for field, dt in CHILD.items():
            rows = d.get(field) or []
            if not rows:
                row.pop(field, None)
                continue
            child_rows += len(rows)
            row[field] = [
                {k: v for k, v in r.as_dict().items()
                 if k not in ("name", "owner", "creation", "modified", "modified_by", "docstatus",
                              "parent", "parenttype", "parentfield", "idx", "doctype")
                 and v not in (None, "")}
                for r in rows
            ]
        docs.append(row)

    json.dump(docs, open(OUT + "avocado_entries.json", "w"), default=str)
    print("dumped {} parents, {} child rows".format(len(docs), child_rows))
    print("bytes:", len(open(OUT + "avocado_entries.json").read()))
