"""Push Scouting Entries to the target site, timed.

Two things make this not a straight copy.

TREE NAMES DIFFER. kaitet's Orchard Trees carry legacy import codes
(23HA_BLK1_ROW1_T1); the target's were generated by the field automation
("BLOCK BLK 1 - KL - Row 1 - Tree 1"). The row and the tree number are common to
both, so the name is rebuilt from them. Verified at 100% on a 1,000-tree sample
before this was written — a miss is reported, never guessed past.

NAMES ARE NOT PRESERVED. Scouting Entry autonames from a naming series, so the
name Frappe assigns on the target has nothing to do with the source's. Checking
"is this already there?" by name never matches, and a re-run inserts everything
a second time — which is exactly what happened on the first avocado push, and
cost a dedupe of 500 documents. Idempotency keys on the observation instead:
who looked, when, and at which plant.

GREENHOUSE NAMES WERE CORRECTED. Torongo GH17/GH18 gained a space, and one
Chepsito greenhouse carries a triple space. kaitet holds both spellings; the
target only the corrected one. Beds and Zones are named after their greenhouse,
so their names are remapped by the same substitution.

    python3 push_scouting.py --crop Avocado --limit 500        # dry run
    python3 push_scouting.py --crop Avocado --apply
"""

from __future__ import annotations

import argparse
import json
import sys
import time

import target as T

DATA = "/tmp/claude-1001/-home-ubuntu-stive-code-frappe15-apps-upande-scp/b6c1bfb1-0cbb-4dc9-8993-2881a8b84c4a/scratchpad/"

# Corrected on the target; kaitet still carries the old spelling too.
WAREHOUSE_REMAP = {
	"Torongo GH17 - KR": "Torongo GH 17 - KR",
	"Torongo GH18 - KR": "Torongo GH 18 - KR",
	"Chepsito GH 15   - KR": "Chepsito GH 15 - KR",
}
BATCH = 50

# What identifies one scouting observation. The document name cannot: it is
# regenerated from a naming series on insert.
KEY_FIELDS = ("date_of_capture", "time_of_capture", "scouts_name", "crop_scouted",
              "greenhouse", "block", "bed", "zone", "tree")


def _natural_key(row):
	return tuple(str(row.get(f) or "") for f in KEY_FIELDS)


def _remap_geometry(value):
	"""Bed and Zone names embed their greenhouse, so they move with the rename."""
	if not value:
		return value
	for old, new in WAREHOUSE_REMAP.items():
		if value.startswith(old):
			return new + value[len(old):]
	return value


def main():
	p = argparse.ArgumentParser()
	p.add_argument("--apply", action="store_true")
	p.add_argument("--limit", type=int, default=0, help="cap the number pushed")
	p.add_argument("--batch", type=int, default=BATCH)
	p.add_argument("--file", default="avocado_entries.json",
	               help="dump to push; repeatable, or a glob like rose_slice_*.json")
	args = p.parse_args()

	import glob as _glob

	files = sorted(_glob.glob(DATA + args.file)) or [DATA + args.file]
	t = T.Target()
	print(t.describe())
	print("mode:", "APPLY" if args.apply else "dry run")
	print("slices: {}".format(len(files)))

	tree_map = json.load(open(DATA + "tree_map.json"))

	# Read the target's existing observations ONCE. Re-reading per slice costs a
	# 290k-row fetch that grows as the push proceeds; instead the set is held and
	# added to, so a resumed or repeated run is still exact.
	print("reading what the target already holds ...", flush=True)
	t1 = time.time()
	present = {_natural_key(r) for r in t.get_list("Scouting Entry", fields=list(KEY_FIELDS), limit=0)}
	print("  {} observation(s) already there ({:.1f}s)".format(len(present), time.time() - t1))

	grand_ok = grand_fail = grand_skip = 0
	errors = []
	started = time.time()

	for fi, path in enumerate(files, 1):
		docs = json.load(open(path))
		if args.limit:
			docs = docs[: args.limit]

		remapped = 0
		unmapped_trees = set()
		for d in docs:
			for f in ("greenhouse", "block"):
				if d.get(f) in WAREHOUSE_REMAP:
					d[f] = WAREHOUSE_REMAP[d[f]]
					remapped += 1
			for f in ("bed", "row", "zone"):
				if d.get(f):
					new = _remap_geometry(d[f])
					if new != d[f]:
						d[f] = new
						remapped += 1
			if d.get("tree"):
				mapped = tree_map.get(d["tree"])
				if mapped:
					d["tree"] = mapped
				else:
					unmapped_trees.add(d["tree"])

		todo = []
		for d in docs:
			k = _natural_key(d)
			if k in present or (d.get("tree") in unmapped_trees and d.get("tree")):
				grand_skip += 1
				continue
			present.add(k)          # collapses exact duplicates within the source too
			d.pop("name", None)     # the target assigns its own from the naming series
			todo.append(d)

		label = path.rsplit("/", 1)[-1]
		print("\n[{}/{}] {}  {} docs, {} remapped, {} skipped -> pushing {}".format(
			fi, len(files), label, len(docs), remapped, len(docs) - len(todo), len(todo)), flush=True)
		if unmapped_trees:
			print("    ! {} unmapped tree name(s), those entries skipped".format(len(unmapped_trees)))
		if not args.apply or not todo:
			continue

		ok = fail = 0
		t0 = time.time()
		for i in range(0, len(todo), args.batch):
			chunk = todo[i:i + args.batch]
			r = t._request("POST", "/api/method/frappe.client.insert_many",
			               json={"docs": chunk}, timeout=900)
			if r.ok:
				ok += len(chunk)
			else:
				# insert_many can apply part of a batch before erroring, so the
				# retry has to know what actually landed. Re-reading the keys for
				# just this batch's window is cheap next to double-inserting.
				batch_keys = {_natural_key(d) for d in chunk}
				landed = set()
				probe = t.get_list(
					"Scouting Entry", fields=list(KEY_FIELDS),
					filters={"date_of_capture": ["in", sorted({d.get("date_of_capture") for d in chunk if d.get("date_of_capture")})]},
					limit=0,
				)
				for pr in probe:
					k2 = _natural_key(pr)
					if k2 in batch_keys:
						landed.add(k2)
				if landed:
					print("      batch failed after applying {} of {} — retrying the rest".format(
						len(landed), len(chunk)), flush=True)
				ok += len(landed)
				for d in chunk:
					if _natural_key(d) in landed:
						continue
					good, res = t.insert("Scouting Entry", d)
					if good:
						ok += 1
					else:
						fail += 1
						if len(errors) < 8:
							errors.append((str(_natural_key(d))[:70], str(res)[:130]))
						if fail <= 3:
							# Say it now, not in the summary forty minutes later.
							print("      ! insert failed: {}".format(str(res)[:200]), flush=True)
			done = i + len(chunk)
			if done % (args.batch * 20) == 0 or done >= len(todo):
				rate = done / max(time.time() - t0, 0.001)
				print("    {:>6}/{}  {:>6.1f}/sec".format(done, len(todo), rate), flush=True)
		grand_ok += ok
		grand_fail += fail
		print("    slice done: {} inserted, {} failed in {:.1f}s".format(ok, fail, time.time() - t0), flush=True)
		if fail:
			# Per slice, so a transient wobble is visible while it is happening
			# rather than buried in the final summary.
			print("    {} failure(s) in this slice — re-run to fill them; the push is"
			      " idempotent on the observation key.".format(fail), flush=True)

	elapsed = time.time() - started
	print("\n" + "=" * 62)
	print("{} inserted, {} skipped, {} failed in {:.1f} min ({:.1f}/sec)".format(
		grand_ok, grand_skip, grand_fail, elapsed / 60, grand_ok / max(elapsed, 0.001)))
	for n, e in errors:
		print("  FAILED {}: {}".format(n, e))
	return 1 if grand_fail else 0


if __name__ == "__main__":
	sys.exit(main())
